### ISSUE TITLE
Base.Events: Event [payments.validated] callback resulted in an exception: TypeError: Cannot read property 'nonce' of undefined

### ISSUE THREAD

**Issue by hrncek** [braintree/braintree-web-drop-in#531]
### General information

dropin 1.19.0
Production
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

### Issue description

Random errors in console log during using of credit card and paying

https://includes.ccdc02.com/cardinalcruise/v1/ec76e625fd00ce8210aa/1.ec76e625fd00ce8210aa.songbird.js
Base.Events: Event [payments.setupComplete] callback resulted in an exception: TypeError: i._getDfReferenceIdResolveFunction is not a function

and
https://includes.ccdc02.com/cardinalcruise/v1/ec76e625fd00ce8210aa/1.ec76e625fd00ce8210aa.songbird.js
Base.Events: Event [payments.validated] callback resulted in an exception: TypeError: Cannot read property 'nonce' of undefined

Using 3DS

```js
// Initialization
braintree.dropin.create({
                authorization: self.braintreeToken,
                container: '#braintree-payment-form',
                paypal: {
                    flow: 'vault',
                    buttonStyle: {
                        color: 'blue',
                        shape: 'rect',
                        size: 'medium'
                    }
                },
                threeDSecure: {
                    amount: self.price()
                }
            }, function (createErr, instance) {
                if (createErr) {
                    failedToInitialize();
                }
                self.braintreeInstance = instance;
            });
```

**Comment by crookedneighbor** [comment]
Added code blocks around your snippet to make it a little easier to read. 

Do you have a staging site where we can inspect the error that is occurring?

**Comment by hrncek** [comment]
Unfortunately no, but I can provide sources if needed to you on private

**Comment by hrncek** [comment]
Also this one during initialization

1.ec76e625fd00ce8210aa.songbird.js:17 Base.Message.Init: Init completed slowly
n.cerror @ 1.ec76e625fd00ce8210aa.songbird.js:17
n.sendLogItemsConsole @ 1.ec76e625fd00ce8210aa.songbird.js:17
i.sendBatch @ 1.ec76e625fd00ce8210aa.songbird.js:17
i.log @ 1.ec76e625fd00ce8210aa.songbird.js:17
t.log @ 1.ec76e625fd00ce8210aa.songbird.js:17
t.error @ 1.ec76e625fd00ce8210aa.songbird.js:17
(anonymous) @ 12.ec76e625fd00ce8210aa.songbird.js:2

**Comment by crookedneighbor** [comment]
Send a reproducible example to: https://help.braintreepayments.com/

Please provide a sample client token as well.

**Comment by hrncek** [comment]
Hey I created test environment: https://wachete-test-ne.azurewebsites.net/
Click sign in -> enter email hrncek@gmail.com and password testing
Click -> profile -> Buy subscription -> Start free 7 days trial -> Fill company name and choose country -> click next

When braintree loads the Error Base.Message.Init: Init completed slowly 
shows in console.

If you would enter Credit card and continue the other error will pop up

**Comment by Adam4224** [comment]
I'm getting the exact same issue at braintree.dropin.create. Contents of my console log:

`VM3048:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.paypal.com/xoplatform/logger/api/logger with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ VM3048:1
(anonymous) @ checkout.min.js:1
e @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
v @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
_ @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
l @ checkout.min.js:1
o.dispatch @ checkout.min.js:1
o.then @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
setTimeout (async)
A @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
l @ checkout.min.js:1
o.dispatch @ checkout.min.js:1
o.resolve @ checkout.min.js:1
l @ checkout.min.js:1
o.dispatch @ checkout.min.js:1
o.resolve @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
Promise.then (async)
(anonymous) @ checkout.min.js:1
e @ checkout.min.js:1
e.resolve @ checkout.min.js:1
e.try @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
a @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
a @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
5.83a3dc284ae5fa04311c.songbird.js:2 Base.Events: Event [payments.setupComplete] callback resulted in an exception: TypeError: i._getDfReferenceIdResolveFunction is not a function
n.cerror @ 5.83a3dc284ae5fa04311c.songbird.js:2
n.sendLogItemsConsole @ 5.83a3dc284ae5fa04311c.songbird.js:2
i.sendBatch @ 5.83a3dc284ae5fa04311c.songbird.js:2
i.log @ 5.83a3dc284ae5fa04311c.songbird.js:2
t.log @ 5.83a3dc284ae5fa04311c.songbird.js:2
t.error @ 5.83a3dc284ae5fa04311c.songbird.js:2
logRouter @ 5.83a3dc284ae5fa04311c.songbird.js:2
h @ 5.83a3dc284ae5fa04311c.songbird.js:1
(anonymous) @ 5.83a3dc284ae5fa04311c.songbird.js:2
i @ 5.83a3dc284ae5fa04311c.songbird.js:1
An @ 5.83a3dc284ae5fa04311c.songbird.js:1
publish @ 5.83a3dc284ae5fa04311c.songbird.js:2
h @ 5.83a3dc284ae5fa04311c.songbird.js:1
processSetup @ 5.83a3dc284ae5fa04311c.songbird.js:81
r @ 5.83a3dc284ae5fa04311c.songbird.js:1
s @ 5.83a3dc284ae5fa04311c.songbird.js:1
(anonymous) @ 5.83a3dc284ae5fa04311c.songbird.js:2
i @ 5.83a3dc284ae5fa04311c.songbird.js:1
An @ 5.83a3dc284ae5fa04311c.songbird.js:1
publish @ 5.83a3dc284ae5fa04311c.songbird.js:2
r @ 5.83a3dc284ae5fa04311c.songbird.js:1
s @ 5.83a3dc284ae5fa04311c.songbird.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
(anonymous) @ dropin.min.js:1
r._setupSongbird @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
a.initialize @ dropin.min.js:1
I._setUpThreeDSecure @ dropin.min.js:1
I._setUpDependenciesAndViews @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
I._initialize @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
u @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
setUpBraintree @ Payment:703
customOperationInit @ Payment:751
OperationHelper.initOperations @ operationHelper.js:182
OperationHelper.routeOperationResult @ operationHelper.js:340
success @ Payment:688
fire @ jquery-1.10.2.js:3048
fireWith @ jquery-1.10.2.js:3160
done @ jquery-1.10.2.js:8235
callback @ jquery-1.10.2.js:8778
XMLHttpRequest.send (async)
(anonymous) @ VM3048:1
send @ jquery-1.10.2.js:8706
ajax @ jquery-1.10.2.js:8136
onPaymentMethodReceived @ Payment:680
(anonymous) @ Payment:650
(anonymous) @ dropin.min.js:1
setTimeout (async)
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
t.exports @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
paymentRequest @ Payment:640
(anonymous) @ Payment:601
dispatch @ jquery-1.10.2.js:5095
elemData.handle @ jquery-1.10.2.js:4766
VM3048:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.paypal.com/xoplatform/logger/api/logger with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ VM3048:1
(anonymous) @ checkout.min.js:1
e @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
v @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
_ @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
l @ checkout.min.js:1
o.dispatch @ checkout.min.js:1
o.then @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
setTimeout (async)
A @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
e.try @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
n @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
e.try @ checkout.min.js:1
a.tryInit @ checkout.min.js:1
a.render @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
e.try @ checkout.min.js:1
a.render @ checkout.min.js:1
callOriginal @ checkout.min.js:1
(anonymous) @ checkout.min.js:1
e.<computed> @ checkout.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
initialize @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
_initialize @ dropin.min.js:1
f @ dropin.min.js:1
I._setUpDependenciesAndViews @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
I._initialize @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
u @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
setUpBraintree @ Payment:703
customOperationInit @ Payment:751
OperationHelper.initOperations @ operationHelper.js:182
OperationHelper.routeOperationResult @ operationHelper.js:340
success @ Payment:688
fire @ jquery-1.10.2.js:3048
fireWith @ jquery-1.10.2.js:3160
done @ jquery-1.10.2.js:8235
callback @ jquery-1.10.2.js:8778
XMLHttpRequest.send (async)
(anonymous) @ VM3048:1
send @ jquery-1.10.2.js:8706
ajax @ jquery-1.10.2.js:8136
onPaymentMethodReceived @ Payment:680
(anonymous) @ Payment:650
(anonymous) @ dropin.min.js:1
setTimeout (async)
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
Promise.then (async)
t.exports @ dropin.min.js:1
(anonymous) @ dropin.min.js:1
paymentRequest @ Payment:640
(anonymous) @ Payment:601
dispatch @ jquery-1.10.2.js:5095
elemData.handle @ jquery-1.10.2.js:4766`

**Comment by hgshoggins** [comment]
Randomly happening to me as well on Firefox.
The console reads:
```
Base.Events: Event [payments.setupComplete] callback resulted in an exception: TypeError: self._getDfReferenceIdResolveFunction is not a function
```
Although I cannot see a direct link, it seems that this error then leads to a `TypeError: "payload is undefined"` after `instance.requestPaymentMethod(function (requestPaymentMethodErr, payload)` is fired, and so the nonce is never generated and the transaction cannot complete.

Braintree-web version is `3.50.0`
Braintree-web-drop-in version is `1.19.0`

Both are loaded in a _browserified_ script with modules retrieved from `npm`.

**Comment by crookedneighbor** [comment]
^ we just figured out that error this morning. Hoping to get a release out this week.

**Comment by crookedneighbor** [comment]
This is fixed in the underlying SDK. The next release of Drop-in will include the fix. Will update here when it's out.

**Comment by hgshoggins** [comment]
Version `3.50.1` of `braintree-web` is out on `npm`, however I'm still getting the same error.

**Comment by crookedneighbor** [comment]
@hgshoggins That's because the underlying sdk needed to be updated in Drop-in, which we've just done in v1.20.0. Issue should be fixed now.

**Comment by fzan** [comment]
got this error today on braintree-we-drop-in 1.20.1.

That's the full stacktrace:
![image](https://user-images.githubusercontent.com/6927527/65427823-7c242800-de13-11e9-80f2-75f2dbd15079.png)

**Comment by hgshoggins** [comment]
Are you using the latest version(s)? My problems disappeared with up-to-date libraries.

**Comment by fzan** [comment]
yes. The version is ^1.20.1 in my package.json.

Please note that is in a sandbox environment, still not going live

**Comment by crookedneighbor** [comment]
@fzan please contact our support team so we can figure out exactly what went wrong.

https://help.braintreepayments.com/

**Comment by tassamartz** [comment]
I faced the same issue with the latest version 1.22.1, however when trying with the version 1.20.2 it is working fine. Could you please provide an update on the issue here ?

**Comment by crookedneighbor** [comment]
@tassamartz please contact our support team with steps to reproduce and we'd be happy to look into it and fix it if the problem is at the SDK level.

https://help.braintreepayments.com/
